### ISSUE TITLE
(vpython issue) compound objects crash vpython

### ISSUE THREAD

**Issue by pmelanson** [OCESS/orbitx#41]
We got the following error when making a list of triangles, then making a compound object of them:

```
Exception ignored in: <function standardAttributes.__del__ at 0x00000279BFAD1730>
Traceback (most recent call last):
  File "C:\Users\Patrick\orbit\orbitx\venv\lib\site-packages\vpython\vpython.py", line 1135, in __del__
    super(standardAttributes, self).__del__()
  File "C:\Users\Patrick\orbit\orbitx\venv\lib\site-packages\vpython\vpython.py", line 354, in __del__
    cmd = {"cmd": "delete", "idx": self.idx}
AttributeError: 'compound' object has no attribute 'idx'
```

**Comment by pmelanson** [comment]
@xxxyyyqqq12345 I think I fixed it with 0cc1736, lmk if you have problems still, especially "vpython has no attribute no_notebook"
